### ISSUE TITLE
Compile error after update to 2026.7.0

### ISSUE THREAD

**Issue by PapaGei7** [oxan/esphome-stream-server#72]
Hi,

after update of ESPHome Device Builder to 2026.7.0 I get a compile error:
`Compiling .pioenvs/visonicinterface/src/esphome/components/switch/automation.cpp.o`
`In file included from src/esphome/core/gpio.h:6,`
`                 from src/esphome/core/hal.h:5,`
`                 from src/esphome/core/component.h:9,`
`                 from src/esphome/components/stream_server/stream_server.h:4,`
`                 from src/esphome/components/stream_server/stream_server.cpp:1:`
`src/esphome/components/stream_server/stream_server.cpp: In member function 'virtual void StreamServerComponent::dump_config()':`
`src/esphome/components/stream_server/stream_server.cpp:52:62: error: 'get_use_address' is not a member of 'esphome::network'; did you mean 'get_use_address_to'?`
`   52 |     ESP_LOGCONFIG(TAG, "  Address: %s:%u", esphome::network::get_use_address(), this->port_);`
`      |                                                              ^~~~~~~~~~~~~~~`
`src/esphome/core/log.h:108:101: note: in definition of macro 'esph_log_config'`
`  108 |   ::esphome::esp_log_printf_(ESPHOME_LOG_LEVEL_CONFIG, tag, __LINE__, ESPHOME_LOG_FORMAT(format), ##__VA_ARGS__)`
`      |                                                                                                     ^~~~~~~~~~~`
`src/esphome/components/stream_server/stream_server.cpp:52:5: note: in expansion of macro 'ESP_LOGCONFIG'`
`   52 |     ESP_LOGCONFIG(TAG, "  Address: %s:%u", esphome::network::get_use_address(), this->port_);`
`      |     ^~~~~~~~~~~~~`
`Compiling .pioenvs/visonicinterface/src/esphome/components/switch/switch.cpp.o`
`*** [.pioenvs/visonicinterface/src/esphome/components/stream_server/stream_server.cpp.o] Error 1`
`========================= [FAILED] Took 67.91 seconds =========================`

Can you help ?

**Comment by grzegorzlabudda** [comment]
I have the same thing

**Comment by EyalRotem** [comment]
there's already a PR for that - #71 
so just wait for it to be merged.

**Comment by danielszilagyi** [comment]
> there's already a PR for that - [#71](https://github.com/oxan/esphome-stream-server/pull/71) so just wait for it to be merged.

or use the forked repo in your esphome config file.

**Comment by EyalRotem** [comment]
Which one?

**Comment by grob6000** [comment]
https://github.com/grob6000/esphome-stream-server

In the external component config, simply swap oxan for grob6000. Once it's merged you can swap back.

**Comment by krekr** [comment]
You can also resolve this locally (⚠️ AI generated):

This compilation failure is caused by a breaking change introduced in the ESPHome internal network API in **ESPHome 2026.7.0+** (you are currently running `2026.8.2`).

### Cause of the Error
ESPHome removed the internal `esphome::network::get_use_address()` function and replaced it with `esphome::network::get_use_address_to(...)` to eliminate heap string allocations. 

The external component you are including in your YAML (`https://github.com/oxan/esphome-stream-server.git`) has not yet been updated upstream to support this API change. In `stream_server.cpp` (around line 52), it attempts to call the old method inside `dump_config()`:

```cpp
ESP_LOGCONFIG(TAG, "  Address: %s:%u", esphome::network::get_use_address(), this->port_);
```

---

### How to Fix It

You can resolve this by hosting a patched copy locally or pointing to a patched fork.

#### Option 1: Run a patched local component (Recommended)

1. Inside your ESPHome configuration directory (where `inventory-interface.yaml` is located), create the directory:
   ```
   components/stream_server
   ```
2. Download or copy the files from [`oxan/esphome-stream-server`](https://github.com/oxan/esphome-stream-server) into this new folder:
   - `__init__.py`
   - `stream_server.h`
   - `stream_server.cpp`
3. Open `stream_server.cpp` and locate line 52 in `StreamServerComponent::dump_config()`:
   ```cpp
   ESP_LOGCONFIG(TAG, "  Address: %s:%u", esphome::network::get_use_address(), this->port_);
   ```
   Replace it with:
   ```cpp
   char buf[esphome::network::USE_ADDRESS_BUFFER_SIZE];
   ESP_LOGCONFIG(TAG, "  Address: %s:%u", esphome::network::get_use_address_to(buf), this->port_);
   ```
   *(Alternatively, if you do not need the address printed to the boot logs, you can simplify it to: `ESP_LOGCONFIG(TAG, "  Port: %u", this->port_);`)*

4. Update your `inventory-interface.yaml` to load the local component instead of pulling directly from GitHub:
   ```yaml
   external_components:
     - source:
         type: local
         path: components
   ```
   *(Or if you place the folder under `custom_components/stream_server/`, you can remove the `external_components:` block entirely, as ESPHome loads from `custom_components/` automatically).*

5. Clean the build files and recompile:
   - In the ESPHome Web UI: click the **3 dots** on the device card and select **Clean Build Files**, then click **Install**.
   - Or via CLI: `esphome clean inventory-interface.yaml && esphome run inventory-interface.yaml`

---

#### Option 2: Fork the repository
If you manage multiple devices or prefer keeping it in Git:
1. Fork `oxan/esphome-stream-server` to your own GitHub account.
2. Apply the change above to `stream_server.cpp`.
3. Update your YAML:
   ```yaml
   external_components:
     - source: github://<your-username>/esphome-stream-server
       refresh: always
   ```

**Comment by EyalRotem** [comment]
It is already fixed - but not merged
