### PR TITLE
Fix build on esphome 2026.7.0 (get_use_address removed)

### PR DESCRIPTION
**Pull request by jbunting**
esphome 2026.7.0 removed `network::get_use_address()` in favor of the buffer-based `get_use_address_to(std::span<char, USE_ADDRESS_BUFFER_SIZE>)`, so the current code fails to compile on 2026.7.0:

```
error: 'get_use_address' is not a member of 'esphome::network'; did you mean 'get_use_address_to'?
```

This guards the `dump_config()` address log line by `ESPHOME_VERSION_CODE` so it builds on 2026.7.0 while remaining compatible with older esphome. Same pattern already used by tube0013/esphome-components.

Tested: compiles on esphome 2026.7.0 and 2026.6.4.

### CODE REVIEW

**Comment by jbunting** [comment]
Sorry, somehow I missed that #71 was already open.
